### ISSUE TITLE
Массивы при создании заказа

### ISSUE THREAD

**Issue by Avtonom** [mrkody/cdek_sdk#2]
В документации про метод создание заказа "4.    Список заказов на доставку"
Параметры единичны:
2. Order Отправление (заказ)
2.18.   Package  Упаковка (все упаковки передаются в разных тэгах Package)

Сейчас в SDK Order и Package массивы и СДЭК их не принимает: "Неверный формат XML.  Number: ERR_INVALID_XML"

**Comment by Avtonom** [comment]
@mrkody или СДЕК массив то же принимает?

**Comment by mrkody** [comment]
Я Вас не понимаю. Все массивы преобразуются в XML впоследствии.

**Comment by Avtonom** [comment]
@mrkody СДЕК пишет в документации что ждет один заказ и один пакет. Ваша реализация отправляет ему только список заказов и список пакетов.
